title: Phil Bresnahan's personal and professional portfolio
description: > # this means to ignore newlines until "baseurl:"
  I am an oceanographer at Scripps Institution of Oceanography and the head of R&D for the Smartfin Project
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: COAST Lab # add your name
author-img: sunset-pier.jpg # add your photo
about-author: Coastal Ocean Applied Science & Technology Lab at UNCW # add description
social-twitter: insituphile # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: SUPScientist # add your Github handle
social-linkedin: philbresnahanjr # add your Linkedin handle
social-email: bresnahanp@uncw.edu # add your Email address

# Disqus
discus-identifier: philipbresnahan # add your discus identifier

# Tracker
analytics: UA-120442455-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
